// Mocks generated by Mockito 5.4.5 from annotations
// in getx/test/data/datasources/auth_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:getx/core/services/api_config.dart' as _i4;
import 'package:getx/core/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<T> get<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#parser: parser, #headers: headers, #queryParams: queryParams},
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #queryParams: queryParams,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #get,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #queryParams: queryParams,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> post<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #parser: parser,
                #headers: headers,
                #queryParams: queryParams,
                #body: body,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #queryParams: queryParams,
                        #body: body,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #post,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #queryParams: queryParams,
                      #body: body,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> put<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #parser: parser,
                #headers: headers,
                #queryParams: queryParams,
                #body: body,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #queryParams: queryParams,
                        #body: body,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #put,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #queryParams: queryParams,
                      #body: body,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> patch<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #parser: parser,
                #headers: headers,
                #queryParams: queryParams,
                #body: body,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #patch,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #queryParams: queryParams,
                        #body: body,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #patch,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #queryParams: queryParams,
                      #body: body,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> delete<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParams,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #parser: parser,
                #headers: headers,
                #queryParams: queryParams,
                #body: body,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #delete,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #queryParams: queryParams,
                        #body: body,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #delete,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #queryParams: queryParams,
                      #body: body,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> multipart<T>(
    String? path, {
    _i4.JsonParser<T>? parser,
    Map<String, String>? headers,
    Map<String, String>? fields,
    required Map<String, String>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipart,
              [path],
              {
                #parser: parser,
                #headers: headers,
                #fields: fields,
                #files: files,
              },
            ),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #multipart,
                      [path],
                      {
                        #parser: parser,
                        #headers: headers,
                        #fields: fields,
                        #files: files,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #multipart,
                    [path],
                    {
                      #parser: parser,
                      #headers: headers,
                      #fields: fields,
                      #files: files,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);
}
